export const ecoWords = [
    { word: 'acids', description: 'Chemicals that can cause harmful rain.' },
    { word: 'algae', description: 'Aquatic plants that can indicate water quality.' },
    { word: 'algal', description: 'Relating to harmful water blooms.' },
    { word: 'aware', description: 'Being conscious of environmental issues.' },
    { word: 'beach', description: 'Sandy shore often affected by pollution.' },
    { word: 'biome', description: 'A large ecological area with distinct climate.' },
    { word: 'biota', description: 'The animal and plant life in a region.' },
    { word: 'bloom', description: 'When flowers open; a sign of plant health.' },
    { word: 'burns', description: 'Controlled fires to manage forests.' },
    { word: 'caulk', description: 'Sealant that improves home energy efficiency.' },
    { word: 'clean', description: 'Free from dirt or pollution.' },
    { word: 'cloud', description: 'Visible mass of water droplets in the sky.' },
    { word: 'coral', description: 'Marine animals threatened by ocean warming.' },
    { word: 'crops', description: 'Plants grown for food or materials.' },
    { word: 'crude', description: 'Unrefined petroleum extracted from the ground.' },
    { word: 'cycle', description: 'To go through a repeated process, like in recycling.' },
    { word: 'decay', description: 'Natural breakdown of organic materials.' },
    { word: 'delta', description: 'Wetland area formed at the mouth of a river.' },
    { word: 'ditch', description: 'A narrow water channel, often seen near farms.' },
    { word: 'drain', description: 'Channel for water that can carry pollutants.' },
    { word: 'drips', description: 'Tiny leaks of water that can add up over time.' },
    { word: 'dunes', description: 'Sandy hills that protect coastal areas.' },
    { word: 'earth', description: 'The planet we live on.' },
    { word: 'ethic', description: 'Moral principles in eco-friendly living.' },
    { word: 'farms', description: 'Land used for growing food.' },
    { word: 'fauna', description: 'Animal life in a particular region.' },
    { word: 'field', description: 'An open land area often used for farming.' },
    { word: 'flood', description: 'Overflow of water that can result from climate change.' },
    { word: 'flora', description: 'Plant life in a particular region.' },
    { word: 'frack', description: 'Controversial method of extracting natural gas.' },
    { word: 'fresh', description: 'Clean and unpolluted condition.' },
    { word: 'frost', description: 'Ice crystals formed during cold weather.' },
    { word: 'fumes', description: 'Gases that can pollute the air.' },
    { word: 'fungi', description: 'Organisms that help decompose organic matter.' },
    { word: 'glass', description: 'Material that can be recycled indefinitely.' },
    { word: 'grain', description: 'Small, dry seeds used as food and for farming.' },
    { word: 'green', description: 'A color associated with eco-friendliness.' },
    { word: 'grove', description: 'A small group of trees supporting biodiversity.' },
    { word: 'gully', description: 'A water-carved channel that can lead to erosion.' },
    { word: 'humid', description: 'Moisture in air, affected by climate change.' },
    { word: 'hydro', description: 'Energy derived from flowing water.' },
    { word: 'lakes', description: 'Large bodies of freshwater.' },
    { word: 'leaks', description: 'Water or gas escaping, often a waste issue.' },
    { word: 'lemon', description: 'A citrus fruit; organic waste can go in compost.' },
    { word: 'metal', description: 'Recyclable material like aluminum or steel.' },
    { word: 'micro', description: 'Short for "microplastics"—tiny harmful plastic particles.' },
    { word: 'miner', description: 'A person who extracts natural resources from Earth.' },
    { word: 'molds', description: 'Fungi that break down organic materials.' },
    { word: 'mulch', description: 'Material spread around plants to enrich soil.' },
    { word: 'nexus', description: 'A connection or link, often used in sustainability discussions.' },
    { word: 'ocean', description: 'A large body of saltwater covering most of Earth.' },
    { word: 'organ', description: 'Relating to organic farming (no synthetic chemicals).' },
    { word: 'ozone', description: 'Atmospheric layer protecting Earth from UV rays.' },
    { word: 'paper', description: 'Material often recycled to save trees.' },
    { word: 'parks', description: 'Protected natural areas for conservation.' },
    { word: 'plant', description: 'A living organism that grows in soil.' },
    { word: 'polar', description: 'Relating to Earths ice-covered regions.' },
    { word: 'ponds', description: 'Small bodies of water supporting ecosystems.' },
    { word: 'power', description: 'Energy used to run homes and businesses.' },
    { word: 'pulps', description: 'Woody material used in paper recycling.' },
    { word: 'renew', description: 'To restore resources like energy or materials.' },
    { word: 'reuse', description: 'Using items again instead of discarding them.' },
    { word: 'rocks', description: 'Solid mineral material from the earth.' },
    { word: 'roots', description: 'The underground part of a plant.' },
    { word: 'rural', description: 'Relating to countryside and natural landscapes.' },
    { word: 'savvy', description: 'Being knowledgeable about eco-friendly choices.' },
    { word: 'seeds', description: 'What plants grow from.' },
    { word: 'shade', description: 'A cool area blocked from direct sunlight, often by trees.' },
    { word: 'smoke', description: 'Visible pollution from fires or industry.' },
    { word: 'smogs', description: 'Air pollution in urban areas.' },
    { word: 'soily', description: 'Relating to healthy soil for farming.' },
    { word: 'solar', description: 'Energy derived from the sun.' },
    { word: 'spill', description: 'Accidental release of harmful substances.' },
    { word: 'storm', description: 'Severe weather that may increase with climate change.' },
    { word: 'tidal', description: 'Relating to ocean movements used for energy.' },
    { word: 'toxic', description: 'Harmful to living organisms and ecosystems.' },
    { word: 'trash', description: 'Discarded waste material.' },
    { word: 'trees', description: 'Plants that provide oxygen and shade.' },
    { word: 'urban', description: 'Relating to cities and their environmental impact.' },
    { word: 'vapor', description: 'Gaseous state of water in the atmosphere.' },
    { word: 'vegan', description: 'A diet avoiding animal products to reduce environmental impact.' },
    { word: 'vines', description: 'Climbing plants that grow quickly.' },
    { word: 'waste', description: 'Unwanted or unusable materials.' },
    { word: 'water', description: 'A vital resource for all living beings.' },
    { word: 'watts', description: 'Units measuring electrical power consumption.' },
    { word: 'weeds', description: 'Wild plants that may compete with crops.' },
    { word: 'winds', description: 'Moving air used to generate clean energy.' },
    { word: 'windy', description: 'Relating to wind energy generation.' },
    { word: 'worms', description: 'Creatures that help break down compost.' }
  ];