export const ecoWords = [
    { word: 'reuse', description: 'Using items again instead of discarding them.' },
    { word: 'solar', description: 'Energy derived from the sun.' },
    { word: 'earth', description: 'The planet we live on.' },
    { word: 'plant', description: 'A living organism that grows in soil.' },
    { word: 'green', description: 'A color associated with eco-friendliness.' },
    { word: 'clean', description: 'Free from dirt or pollution.' },
    { word: 'water', description: 'A vital resource for all living beings.' },
    { word: 'waste', description: 'Unwanted or unusable materials.' },
    { word: 'trees', description: 'Plants that provide oxygen and shade.' },
    { word: 'ocean', description: 'A large body of saltwater covering most of Earth.' },
    { word: 'reuse', description: 'Using items again instead of throwing them away.' },
    { word: 'earth', description: 'Our planet and its natural environment.' },
    { word: 'plant', description: 'Living organisms that grow in soil and produce oxygen.' },
    { word: 'cycle', description: 'A repeated process, like recycling materials.' },
    { word: 'metal', description: 'Material like aluminum that can be recycled.' },
    { word: 'paper', description: 'Product from trees, recyclable for new use.' },
    { word: 'biode', description: 'Short for "biodegradable"—breaks down naturally.' },
    { word: 'ozone', description: 'A layer protecting Earth from harmful sun rays.' },
    { word: 'emiss', description: 'Short for "emissions"—gases released into the air.' },
    { word: 'windy', description: 'Relating to wind energy generation.' },
    { word: 'ecosy', description: 'Short for "ecosystem"—a community of living things.' },
    { word: 'fauna', description: 'Animal life in a specific area.' },
    { word: 'habitat', description: 'Natural environment where organisms live.' },
    { word: 'carbon', description: 'Element linked to climate change and emissions.' },
    { word: 'renew', description: 'To restore or replace resources sustainably.' },
    { word: 'sustain', description: 'To maintain ecological balance and resources.' },
    { word: 'recycle', description: 'Process of converting waste into reusable material.' },
    { word: 'flora', description: 'Plant life in a particular region.' },
    { word: 'caulk', description: 'Sealant that improves home energy efficiency.' },
    { word: 'biome', description: 'A large naturally occurring community of flora and fauna.' },
    { word: 'trash', description: 'Discarded waste material.' },
    { word: 'mulch', description: 'Material spread around plants to enrich soil.' },
    { word: 'compo', description: 'Decayed organic material used as plant fertilizer.' },
    { word: 'hydro', description: 'Energy derived from flowing water.' },
    { word: 'eco-g', description: 'Products designed to have minimal environmental impact.' },
    { word: 'algae', description: 'Aquatic plants that can indicate water quality.' },
    { word: 'smogs', description: 'Air pollution in urban areas.' },
    { word: 'ozone', description: 'Atmospheric layer that protects from UV rays.' },
    { word: 'winds', description: 'Moving air used to generate clean energy.' },
    { word: 'gully', description: 'A water-carved channel that can lead to erosion.' },
    { word: 'crude', description: 'Unrefined petroleum extracted from the ground.' },
    { word: 'pulps', description: 'Woody material used in paper recycling.' },
    { word: 'worms', description: 'Creatures that help break down compost.' },
    { word: 'delta', description: 'Wetland area formed at the mouth of a river.' },
    { word: 'compa', description: 'Short for compost, where food waste can turn to soil.' },
    { word: 'ecola', description: 'Short for ecology, the study of how organisms relate to their environment.' },
    { word: 'nexus', description: 'A connection or link, often used in sustainability discussions.' },
    { word: 'cycle', description: 'To go through a repeated process, like in recycling.' },
    { word: 'carbon', description: 'A key element related to pollution and climate change.' },
   { word: 'envie', description: 'Short for environment (slang or stylized).' },
   { word: 'frack', description: 'Controversial method of extracting natural gas.' },
   { word: 'lemon', description: 'A citrus fruit; organic waste can go in compost.' },
   { word: 'ditch', description: 'A narrow water channel, often seen near farms.' },

  ];